// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72TAQHCPEENKuM9jvoHQKUDn0_RMOPVo',
    appId: '1:1094666923252:web:8820621729d51cf771c2a1',
    messagingSenderId: '1094666923252',
    projectId: 'food-app-8f283',
    authDomain: 'food-app-8f283.firebaseapp.com',
    storageBucket: 'food-app-8f283.firebasestorage.app',
    measurementId: 'G-E9HV33VRCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ESbS9ViHXc_tXuFPxrR-CBWvPVTnWLY',
    appId: '1:1094666923252:android:4af1f265d420ee3171c2a1',
    messagingSenderId: '1094666923252',
    projectId: 'food-app-8f283',
    storageBucket: 'food-app-8f283.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sf_SCi9AAavNxAuw20QBbyIHBm1nR1w',
    appId: '1:1094666923252:ios:265d8bfe89e606c871c2a1',
    messagingSenderId: '1094666923252',
    projectId: 'food-app-8f283',
    storageBucket: 'food-app-8f283.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sf_SCi9AAavNxAuw20QBbyIHBm1nR1w',
    appId: '1:1094666923252:ios:265d8bfe89e606c871c2a1',
    messagingSenderId: '1094666923252',
    projectId: 'food-app-8f283',
    storageBucket: 'food-app-8f283.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA72TAQHCPEENKuM9jvoHQKUDn0_RMOPVo',
    appId: '1:1094666923252:web:7eb8e308f53f41dc71c2a1',
    messagingSenderId: '1094666923252',
    projectId: 'food-app-8f283',
    authDomain: 'food-app-8f283.firebaseapp.com',
    storageBucket: 'food-app-8f283.firebasestorage.app',
    measurementId: 'G-6BECPW36LD',
  );
}
